export const LANGS = [
  { code: "en", name: "English", flag: "🇺🇸" },
  { code: "it", name: "Italiano", flag: "🇮🇹" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "fr", name: "Français", flag: "🇫🇷" },
  { code: "ja", name: "日本語", flag: "🇯🇵" },
  { code: "sv", name: "Svenska", flag: "🇸🇪" },
  { code: "de", name: "Deutsch", flag: "🇩🇪" },
  { code: "no", name: "Norsk", flag: "🇳🇴" },
  { code: "ru", name: "Русский", flag: "🇷🇺" },
  { code: "hu", name: "Magyar", flag: "🇭🇺" },
  { code: "pl", name: "Polski", flag: "🇵🇱" },
  { code: "sl", name: "Slovenčina", flag: "🇸🇰" },
  { code: "ko", name: "한국어", flag: "🇰🇷" },
  { code: "id", name: "Bahasa Indonesia", flag: "🇮🇩" },
];
