export const errorMessages = {
   // ====== log_in / register_2相关（600 段） ======
  601: "user_does_not_exist",
  602: "wrong_password",
  603: "username_cannot_be_empty",
  604: "password_cannot_be_empty",
  605: "transaction_password_cannot_be_empty",
  606: "phone_number_cannot_be_empty",
  607: "gender_cannot_be_empty",
  608: "invitation_code_cannot_be_empty",
  609: "username_already_exists",
  610: "invitation_code_does_not_exist",
  611: "please_enter_password",
  612: "transaction_password_length_must_be_between_6_and_18_characters",
  613: "incorrect_transaction_password",
  614: "user_does_not_exist_or_avatar_is_empty",
  615: "invalid_request_header",
  616: "logout_failed",
  617: "login_failed_unknown_error",
  618: "account_disabled",
  621: "phone_number_has_been_registered",

  // ====== 提现相关（500 段） ======
  501: "not_within_the_allowed_withdrawal_time_frame",
  502: "withdrawal_amount_is_below_the_minimum_limit",
  503: "withdrawal_amount_exceeds_the_maximum_limit",
  504: "incorrect_transaction_password",
  505: "insufficient_number_of_orders",
  506: "there_is_an_unfinished_withdrawal_order",
  507: "insufficient_balance",
  508: "system_configuration_not_available",
  509: "user_does_not_exist",
  510: "user_level_information_is_missing",
  511: "please_try_again_later",
  512: "withdrawal_is_not_enabled",
  513: "withdrawal_method_not_set",
  514: "withdrawal_is_not_available_at_the_moment",
  519: "insufficient_credit_score",

  // ====== 通用 / 上传 / 数据（700 段） ======
  701: "no_data_available",
  703: "upload_failed",

  // ====== 抢单相关（900 段） ======
  901: "system_configuration_not_available",
  902: "not_within_the_allowed_order_taking_time_frame",
  903: "username_cannot_be_empty",
  904: "user_does_not_exist",
  905: "this_user_is_not_allowed_to_take_orders",
  906: "balance_is_below_the_minimum_transaction_amount",
  907: "there_are_pending_orders",
  908: "please_try_again_later",
  909: "your_mission_has_been_completed_please_contact_customer_service",
  910: "invalid_configuration",
  911: "no_suitable_product_or_insufficient_balance",
  912: "invalid_membership_tier_configuration",
  913: "invalid_order",
  914: "invalid_user",
  915: "user_identity_mismatch",
  916: "insufficient_balance",
  917: "order_has_been_completed",
  918: "order_status_does_not_allow_submission",
  919: "we_ll_be_happy_to_help_and_get_back_to_you_once_we_re_online",
  920: "customer_service_is_currently_unavailable",
  921: "please_contact_customer_service_to_enable_the_task",

  // ====== 特殊status码 ======
  200: "no_new_orders_order_submitted_successfully",
  201: "user_has_ongoing_orders_returning_new_order_information",
  2007: "insufficient_user_balance_contact_administrator_often_due_to_insufficient_frozen_funds",

  801: "",
  802: "lottery_not_enabled",
  803: "no_lottery_attempts_remaining",
};