export const errorMessages = {
  // Common request errors
  400: "das.apiErrors.invalidRequestParams",
  404: "das.apiErrors.messageNotFound",

  500: "das.orderErrors.server",

  // Login / registration errors (600 range)
  601: "das.apiErrors.userNotFound",
  602: "das.apiErrors.wrongPassword",
  603: "das.apiErrors.usernameRequired",
  604: "das.apiErrors.passwordRequired",
  605: "das.apiErrors.transactionPasswordRequired",
  606: "das.apiErrors.phoneRequired",
  607: "das.apiErrors.genderRequired",
  608: "das.apiErrors.invitationCodeRequired",
  609: "das.apiErrors.usernameAlreadyExists",
  610: "das.apiErrors.invitationCodeNotFound",
  611: "das.apiErrors.enterPassword",
  612: "das.apiErrors.transactionPasswordLength",
  613: "das.apiErrors.wrongTransactionPassword",
  614: "das.apiErrors.userOrAvatarMissing",
  615: "das.apiErrors.invalidRequestHeader",
  616: "das.apiErrors.logoutFailed",
  617: "das.apiErrors.loginFailedUnknown",
  621: "das.apiErrors.phoneAlreadyExists",
  622: "das.apiErrors.tooManyAttempts",

  // Withdrawal errors (500 range)
  501: "das.apiErrors.withdrawalOutsideAllowedTime",
  502: "das.apiErrors.withdrawalBelowMinimum",
  503: "das.apiErrors.withdrawalAboveMaximum",
  504: "das.apiErrors.wrongTransactionPassword",
  505: "das.apiErrors.insufficientOrderCount",
  506: "das.apiErrors.unfinishedWithdrawalOrder",
  507: "das.apiErrors.insufficientBalance",
  508: "das.apiErrors.systemConfigUnavailable",
  509: "das.apiErrors.userNotFound",
  510: "das.apiErrors.userLevelMissing",
  511: "das.apiErrors.tryAgainLater",
  512: "das.apiErrors.withdrawalDisabled",
  513: "das.apiErrors.withdrawalMethodMissing",
  514: "das.apiErrors.withdrawalUnavailable",
  515: "das.apiErrors.withdrawalInvalidParams",
  516: "das.apiErrors.withdrawalBelowMinimum",
  517: "das.apiErrors.withdrawalAboveMaximum",
  518: "das.apiErrors.withdrawalAccountInUseOrConflict",
  519: "das.apiErrors.platformDailyWithdrawalLimitReached",
  521: "das.apiErrors.insufficientCreditForWithdrawal",
  522: "das.apiErrors.withdrawalBalanceBelowLevelMinimum",
  523: "das.apiErrors.dailyWithdrawalCountLimitReached",
  524: "das.apiErrors.dailyWithdrawalAmountLimitReached",
  525: "das.apiErrors.idempotencyKeyConflict",
  526: "das.apiErrors.withdrawalCredentialInvalid",

  // Common / upload / data errors (700 range)
  701: "das.apiErrors.noData",
  703: "das.apiErrors.uploadFailed",

  // Order-taking errors (900 range)
  901: "das.orderErrors.tradeConfig",
  902: "das.orderErrors.outsideTradingHours",
  903: "das.apiErrors.usernameRequired",
  904: "das.orderErrors.userMissing",
  905: "das.orderErrors.accountRestricted",
  906: "das.orderErrors.minimumBalance",
  907: "das.apiErrors.unfinishedOrder",
  908: "das.orderErrors.busy",
  909: "das.apiErrors.dailyOrderLimitReached",
  910: "das.orderErrors.invalidConfig",
  911: "das.orderErrors.noProduct",
  912: "das.orderErrors.invalidLevel",
  913: "das.orderErrors.orderMissing",
  914: "das.orderErrors.invalidUser",
  915: "das.apiErrors.userIdentityMismatch",
  916: "das.orderErrors.insufficientBalance",
  917: "das.apiErrors.orderCompleted",
  918: "das.orderErrors.orderConflict",
  921: "das.orderErrors.bonusMissing",
  922: "das.orderErrors.bonusUnavailable",
  923: "das.orderErrors.invalidRequest",

  // Special error status
  2007: "das.apiErrors.insufficientUserBalanceFrozen",
};
